### ISSUE TITLE
Scripts are failing

### ISSUE THREAD

**Issue by CyberSauce** [slaet/IntuneTeams#1]
Hey,

I used the Win32 packager and everything looks good. I went to run it and it continuously fails. I ran the script individually from the PS1 and it uploads the background fine locally. Anything I might be missing?

**Comment by CyberSauce** [comment]
It looks like I've got it. Few things to note:

The items in quotes need to be deleted along with .\ so it should look like this:

powershell.exe -executionpolicy bypass -file copyTeamsBG.ps1
powershell.exe -executionpolicy bypass -file copyTeamsBGuninstall.ps1 Select the Install behavior = User

That finally got them deployed, but shows an error. Next item is to work on the detection script.

**Comment by CyberSauce** [comment]
Also, for the detection script towards the top you have a # in front of $pictures. After I took that out and redeployed it shows successful now.

**Comment by slaet** [comment]
sorry for the delayed answer, I should add mail alert when issues comes up.
yes, it should be user, because Teams in local appdata is in the user area.
and thank for the change with the #

**Comment by slaet** [comment]
thx for the update
